application: recipes1520
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: .+/stylesheets
  static_dir: stylesheets

- url: /img
  static_dir: img

- url: /.*
  script: Main.app

libraries:
- name: webapp2
  version: latest